# Generated by Django 5.0.3 on 2024-03-23 22:27

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="default.png",
                upload_to=apps.users.models.Profile.get_upload_path,
            ),
        ),
    ]
