# Generated by Django 5.0.3 on 2024-03-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_name_profile_first_name_profile_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
