# Generated by Django 5.0.3 on 2024-03-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_profile_about_alter_profile_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.CharField(blank=True, max_length=450),
        ),
    ]
