# Generated by Django 5.0.3 on 2024-03-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_profile_about_alter_profile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.CharField(
                blank=True, default="Nothing to say here", max_length=300
            ),
        ),
    ]
