# Generated by Django 5.0.3 on 2024-03-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.CharField(
                blank=True, default="Nothing to say here", max_length=300
            ),
        ),
    ]
