# Generated by Django 5.0.3 on 2024-03-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
    ]
